### PR TITLE
fix(ledger-browser): supabase advisor errors and warnings

### LINKED ISSUE #3551: fix(ledger-browser): supabase advisor errors and warnings
**Describe the bug**

Supabase reports multiple errors and warnings in it's advisor which should be resolved.

**To Reproduce**

- Follow the [setup guide](https://hyperledger.github.io/cacti/cactus/ledger-browser/setup/) using `Supabase Cloud` (not sure if advisor is available on local deployment).
- Install Ethereum and Fabric browser apps using test data setup (e.g. https://hyperledger.github.io/cacti/cactus/ledger-browser/plugin-apps/ethereum-browser/#test-data-setup)
- Go to `Advisors` tab and fix all reported issues.

**Expected behavior**

There should be no errors and warnings in advisor.

**Screenshots**

image

**Additional context**

- Most issues will be solved by enabling RLS on table schemas, see https://supabase.com/docs/guides/database/postgres/row-level-security
- Permissive policy allowing access to all (with an API key) is sufficient for now (since we don't support users).
- Fixes must be applied to persistent plugin schema files (e.g. https://github.com/hyperledger/cacti/blob/main/packages/cactus-plugin-persistence-ethereum/src/main/sql/schema.sql) and tested

### PR DESCRIPTION
**Pull request by musicboy0322**
Primary Change:
* SQL schema
    1. Enable RLS and set policy (Security Advisor, Type of Error)
    2. Set RLS policy (Security Advisor, Type of Info)
    3. Set search_path (Security Advisor, Type of Warning)
    4. Set security_invoker (Security Advisor, Type of Error)
    5. Reset GRANT of "ethereum.token_erc20" (Security Advisor, Type of Warning)
    6. Remove duplicate index (Performance Advisor, Type of Warning)
    7. Add public search path to use uuid_generate_v4()
* Test Code
    1. Upgrade persistence-ethereum-postgresql-db-client.test PostgreSQL version

Fixes #3551

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by outSH — CHANGES_REQUESTED** [review]
Looks great, thank you!

After setting app new DB with updated schemas I'm having the following `Duplicate Index
` warnings, could you please reproduce and resolve them as well?

```
Table fabric.block has identical indexes {block_hash_key,block_hash_unique_idx}. Drop all except one of them

Table fabric.block has identical indexes {block_number_key,block_number_unique_idx}. Drop all except one of them

Table fabric.certificate has identical indexes {certifiate_serial_number_unique,certifiate_serial_number_unique_idx}. Drop all except one of them

**Comment by musicboy0322** [comment]
@outSH Hi! Thanks for the review.

Sorry I missed this part. I'll take care of it. Thanks for pointing it out!

**Comment by musicboy0322** [comment]
@outSH I've fixed the duplicate index issue. Please take another look when you get the chance. Thanks again!

File: packages/cactus-plugin-persistence-fabric/src/main/sql/schema.sql [hunk 1]
```diff
@@ -54,6 +76,9 @@ ALTER TABLE ONLY fabric.block
 CREATE UNIQUE INDEX block_hash_unique_idx ON fabric.block USING btree (hash);
 CREATE UNIQUE INDEX block_number_unique_idx ON fabric.block USING btree (number);
 
+DROP INDEX IF EXISTS fabric.block_hash_unique_idx;
+DROP INDEX IF EXISTS fabric.block_number_unique_idx;
```
Comment (outSH) [inline packages/cactus-plugin-persistence-fabric/src/main/sql/schema.sql:80]: Sorry for nitpicking, but it's better not to create these indexes in a first place, rather then creating and removing them. Please remove these lines

File: packages/cactus-plugin-persistence-fabric/src/main/sql/schema.sql [hunk 2]
```diff
@@ -91,6 +136,8 @@ ALTER TABLE ONLY fabric.certificate
 
 CREATE UNIQUE INDEX certifiate_serial_number_unique_idx ON fabric.certificate USING btree (serial_number);
 
+DROP INDEX IF EXISTS fabric.certifiate_serial_number_unique_idx;
```
Comment (outSH) [inline packages/cactus-plugin-persistence-fabric/src/main/sql/schema.sql:139]: Same as above

**Review by outSH — APPROVED** [review]
Awesome, thanks for additional work! LGTM

BTW remember to re-request the review once you're done with the changes so that reviewer gets notification (the small "refresh" icon next to reviewer name)

image

**Review by petermetz — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@musicboy0322 @outSH It looks good to me, but I see that the tests started failing (or maybe they already were). Could you please double check just to make sure?

Attaching the logs of the failing test job in case it gets auto-deleted later.
[2025-04-23T03:55:26.8339321Z.log](https://github.com/user-attachments/files/19860826/2025-04-23T03.55.26.8339321Z.log)


These are the first few errors from the log:

```
FAIL packages/cactus-plugin-persistence-ethereum/src/test/typescript/integration/persistence-ethereum-postgresql-db-client.test.ts (13.204 s, 1070 MB heap size)
  ● Ethereum persistence PostgreSQL PostgresDatabaseClient tests › Insert single and get all ERC20 token metadata.

    error: unrecognized parameter "security_invoker"

      at Parser.parseErrorMessage (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/index.ts:7:48)

  ● Ethereum persistence PostgreSQL PostgresDatabaseClient tests › Insert single and get all ERC20 token metadata.

    error: relation "ethereum.token_transfer" does not exist

      at Parser.parseErrorMessage (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/index.ts:7:48)

  ● Ethereum persistence PostgreSQL PostgresDatabaseClient tests › Initialize plugin can be called repeatedly and it only updates the last_connected_at

    error: unrecognized parameter "security_invoker"

      at Parser.parseErrorMessage (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/index.ts:7:48)

  ● Ethereum persistence PostgreSQL PostgresDatabaseClient tests › Initialize plugin can be called repeatedly and it only updates the last_connected_at

    error: relation "ethereum.token_transfer" does not exist

      at Parser.parseErrorMessage (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (packages/cactus-plugin-persistence-ethereum/node_modules/pg-protocol/src/index.ts:7:48)

```

**Comment by musicboy0322** [comment]
@petermetz Got it, thanks for pointing it out! I will look into the test failures and fix them.

**Review by petermetz — APPROVED** [review]
@musicboy0322 LGTM, thank you very much for the fixes!
