### PR TITLE
fix(satp-hermes): shutdown of SATP gateway should assure there are no pending transfers before shutting down

### LINKED ISSUE #3756: fix(satp-hermes): shutdown of SATP gateway should assure there are no pending transfers before shutting down
**Describe the bug**

The shutdown code at https://github.com/hyperledger-cacti/cacti/blob/satp-dev/packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts#L585 does not clean up existing sessions. It should wait that all transfers are resolved prior to shutdown. 

**To Reproduce**
NA

**Expected behavior**

A call to gateway.shutdown() should wait for all pending sessions to counterparty gateways to be resolved.

NA

### PR DESCRIPTION
**Pull request by joaoecsde**
Introduces a new function, `verifySessionState`, which upon shutdown verifies if all sessions are concluded. Also a flag was created to prevent new transactions to occur when shutdown was already called.

Additionally, a new type of error is introduced `gateway-error` .

Resolves #3756.
**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

File: packages/cactus-plugin-satp-hermes/src/main/typescript/services/gateway/satp-manager.ts [hunk 1]
```diff
@@ -308,6 +309,17 @@ export class SATPManager {
     return this.satpHandlers.get(type);
   }
 
+  public getSATPSessionState(): boolean {
```
Comment (LordKubaya) [inline packages/cactus-plugin-satp-hermes/src/main/typescript/services/gateway/satp-manager.ts:312]: Document this method

File: packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts [hunk 2]
```diff
@@ -649,4 +650,29 @@ export class SATPGateway implements IPluginWebService, ICactusPlugin {
...
+      this.logger.debug(`Inside: ${status}`);
+      status = await manager.getSATPSessionState();
+      if (!status) {
+        this.logger.info("Sessions are still pending");
+        await new Promise(resolve => setTimeout(resolve, 20000));
+      }
+    }
+    this.logger.info("All sessions are concluded");
+  }
 }
```
Comment (LordKubaya) [inline packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts:678]: This is a blocker function, change this to use a Cron job: 
https://stackoverflow.com/questions/64777543/how-to-make-a-cron-job-for-a-typescript-class-method

**Review by LordKubaya — CHANGES_REQUESTED** [review]
LGTM, but the method of verifying sessions should done in a different approach.

File: packages/cactus-plugin-satp-hermes/src/main/typescript/core/satp-session.ts [hunk 3]
```diff
@@ -224,6 +224,12 @@ export class SATPSession {
     return this.serverSessionData?.id || this.clientSessionData?.id || "";
   }
 
+  public getSessionState(): State {
+    console.log("serverSessionId: ", this.serverSessionData?.state);
```
Comment (RafaelAPB) [inline packages/cactus-plugin-satp-hermes/src/main/typescript/core/satp-session.ts:228]: please use the component logger instead of console.log

File: packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts [hunk 4]
```diff
@@ -649,4 +650,29 @@ export class SATPGateway implements IPluginWebService, ICactusPlugin {
...
+  private async verifySessionsState(): Promise<void> {
+    const fnTag = `${this.className}#verifySessionsState()`;
+    this.logger.trace(`Entering ${fnTag}`);
+    if (!this.BLODispatcher) {
+      throw new Error(`Cannot ${fnTag} because BLODispatcher is erroneous`);
+    }
+    this.BLODispatcher.setInitiateShutdown();
+    const manager = await this.BLODispatcher.getManager();
+    let status = false;
+    while (!status) {
```
Comment (RafaelAPB) [inline packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts:668]: there is a potential infinite loop. this function might block, and we need to decide if this is desirable behaviour. On one hand, the gateway cannot handle anything else; on the other, it should not serve new requests. So there should be a middle-term that allows the gateway to keep serving other requests (namely admin) while not initiating new transfers nor blocking.

Besides, we might want to include a timeout, since something can be broken in the manager (in particular if there is a hanging SATP transfer, communicating with a counterparty gateway).

**Review by RafaelAPB — CHANGES_REQUESTED** [review]

File: packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts [hunk 5]
```diff
@@ -649,4 +653,51 @@ export class SATPGateway implements IPluginWebService, ICactusPlugin {
...
+   * Verify the state of the sessions before shutting down the server.
+   * This method is called before the server is shut down and awaits ensure that 
+   * all sessions are concluded before the server is terminated.
+   * After all sessions are concluded, the job is cancelled.
+  */
+  private async verifySessionsState(): Promise<void> {
+    const fnTag = `${this.className}#verifySessionsState()`;
+    this.logger.trace(`Entering ${fnTag}`);
+    if (!this.BLODispatcher) {
+      throw new Error(`Cannot ${fnTag} because BLODispatcher is erroneous`);
```
Comment (LordKubaya) [inline packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts:667]: Change this to a Runtime Error

**Review by LordKubaya — CHANGES_REQUESTED** [review]
LGTM, just change the error type.
