### PR TITLE
ci(weaver): update network-setups fabric setupCC.sh

### LINKED ISSUE #3679: bug(weaver-networksetups-fabric): issues with fabric sample network
**Describe the bug**

Fabric Testnet in weaver v2.1.0 is not launched because of "No such file or directory" error.

**To Reproduce**

If you execute the following command, error is occured.
```sh
$ cd /weaver/tests/network-setups/fabric/dev/scripts/
$ make start-interop
```

**Logs/Stack traces**

```sh
$ make start-interop
./scripts/setupCC.sh
go: downloading github.com/hyperledger-cacti/cacti/weaver/core/network/fabric-interop-cc/contracts/interop/v2 v2.1.0
go: downloading github.com/hyperledger-cacti/cacti v2.1.0+incompatible
go: downloading github.com/ethereum/go-ethereum v1.13.15
go: downloading github.com/golang/protobuf v1.5.4
go: downloading github.com/hyperledger-cacti/cacti/weaver/common/protos-go/v2 v2.1.0
go: downloading github.com/hyperledger-cacti/cacti/weaver/core/network/fabric-interop-cc/libs/assetexchange/v2 v2.1.0
go: downloading github.com/hyperledger-cacti/cacti/weaver/core/network/fabric-interop-cc/libs/utils/v2 v2.1.0
...
cp: cannot stat ‘/home/ec2-user/work/cacti/weaver/tests/network-setups/fabric/dev/../shared/tmp/pkg/mod/github.com/hyperledger-cacti/cacti/weaver/core/network/fabric-interop-cc/contracts/interop/v2@v2.0.0’: No such file or directory
chmod: cannot access ‘/home/ec2-user/work/cacti/weaver/tests/network-setups/fabric/dev/../shared/chaincode/interop’: No such file or directory
cp -r ../network-artifacts/network1/* ../shared/network1/
```

### PR DESCRIPTION
**Pull request by dnakashima**
Primary Changes
---------------
1. Fixed network-setups fabric setupCC.sh:
weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh

Peter's Changes
---------------
1. Fixed the commit message syntax so that it passes the linter

Fixes: #3679

Co-Authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Signed-off-by: Daiki.Nakashima <Nakashima.Daiki@df.MitsubishiElectric.co.jp>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by dnakashima** [comment]
The reason why this error is that variable "CACTI_VERSION" is not collect. So this patch can get latest version of Cacti from  [VERSION](https://github.com/hyperledger-cacti/cacti/blob/main/weaver/core/network/fabric-interop-cc/contracts/interop/VERSION) file.

File: weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh [hunk 1]
```diff
@@ -4,7 +4,7 @@
 
 directory=$(dirname $0)
 
-CACTI_VERSION=v2.0.0
+CACTI_VERSION="v$(head -n 1 $PWD/../../../../core/network/fabric-interop-cc/contracts/interop/VERSION)"
```
Comment (petermetz) [inline weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh:7]: @dnakashima This seems to hardcode the behavior in  way that forces people to run the script only from a specific given sub-directory.

What that means is that if I ran this script from the project root like 
```sh
$ ./weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh
```

Then it would crash with some error that it can't find the `VERSION` because the $PWD would evaluate to the project  root and then your `../../../../` would just point to some random, non-existent directory path on my file-system outside of the cacti project sources.

What I recommend to fix this is to anchor the paths to the path of the script itself the way the `ci.sh`  script does it:

```sh
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
```

After which you can reach the version file like `"$SCRIPT_DIR/../../../../core/network/fabric-interop-cc/contracts/interop/VERSION'` (or something similar) and with this way the script will function correctly regardless of which directory my shell was in at the time of the script invocation.

I wrote all this code just from memory so there might be issues with it, but please let me know what you think!

Comment (dnakashima) [reply weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh]: @petermetz Thank you for your comment. I did not consider the directory where setupCC.sh is called. So I modify how to get the path of VERSION file.

**Review by outSH — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@dnakashima Please correct the commit subject to appease the linter. I also recommend using the commit type `build` or `ci` or `test` instead of `fix` because `fix` implies a fix in the production code.

File: weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh (hunk 1 above)
Comment (petermetz) [reply weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh]: @dnakashima My pleasure! Thank you for the improvements!

**Comment by petermetz** [comment]
@dnakashima Please also squash the commits together and make sure that the commit subject and the PR title are consistent. Right now there are multiple commits and they both have invalid commit subjects.

image

**Comment by dnakashima** [comment]
@petermetz Thank you for your comment again. I squashed 2 commits and modified the PR title and commit message. So please check it.

**Review by petermetz — CHANGES_REQUESTED** [review]
@dnakashima Thank you for the updates. The commit linter is still failing, please fix that as well.

**Comment by dnakashima** [comment]
@petermetz I have added "colon" and space to the title after prefix and then linter was OK. Please check it again.

**Comment by dnakashima** [comment]
@petermetz Could you check this PR? The commit linter is OK.

**Comment by petermetz** [comment]
@dnakashima Sorry for the slow response! Let me re-review!

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
@dnakashima It's still broken. Let me show you what it needs, BRB

```sh
Error: You have commit messages with errors

⧗   input: ci(weaver)update network-setups fabric setupCC.sh

Primary Changes
---------------
1. Fixed network-setups fabric setupCC.sh:
weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh

Fixes: #3679

Signed-off-by: Daiki.Nakashima <Nakashima.Daiki@df.MitsubishiElectric.co.jp>
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

```

**Comment by dnakashima** [comment]
@petermetz Thank you for your re-review and merge commit!!
